/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Java_MysqlConn;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Java_MysqlConn extends javax.swing.JFrame {

   
    
    public Java_MysqlConn() {
        initComponents();
        table_update();
        
    }
            Connection con1;
            PreparedStatement insert;
            
            private void table_update()
            {
            int c;
            
            String film= txtfilm.getText();
            String naziv= txtnaziv.getText();
            String reziser= txtreziser.getText();
            String zanr= txtzanr.getText();
            String ocjena= txtocjena.getText();
            String godina= txtgodina.getText();
        
         
            
            
            try{  
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/linda","root","");
            insert = con1.prepareStatement("select*from record");
            
            ResultSet rs = insert.executeQuery();
            ResultSetMetaData Rss = rs.getMetaData();
            c = Rss.getColumnCount();
                
            DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
            
            Df.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2 = new Vector();
                for(int a=1; a<=c; a++)
                {
                v2.add(rs.getString("id"));
                v2.add(rs.getString("filmID"));
                v2.add(rs.getString("naziv"));
                v2.add(rs.getString("reziser"));
                v2.add(rs.getString("zanr"));
                v2.add(rs.getString("ocjena"));
                v2.add(rs.getString("godina"));      
              }
                
                Df.addRow(v2);
            }
            
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Java_MysqlConn.class.getName()).log(Level.SEVERE, null, ex);
        }
         catch (SQLException ex) {
            Logger.getLogger(Java_MysqlConn.class.getName()).log(Level.SEVERE, null, ex);
        }  
            }
             
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //=================================================Function=========================================
    
   
    
    
    
    
    
    //=================================================EndFunction=========================================

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtocjena = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnaziv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtreziser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtgodina = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtfilm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtzanr = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jbtnAdd = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnedit = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Ocjena");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        txtocjena.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtocjena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtocjenaActionPerformed(evt);
            }
        });
        jPanel3.add(txtocjena, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 500, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Naziv");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 110, 30));

        txtnaziv.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(txtnaziv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 500, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Režiser");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        txtreziser.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(txtreziser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 500, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Godina");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        txtgodina.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtgodina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgodinaActionPerformed(evt);
            }
        });
        jPanel3.add(txtgodina, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 500, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Film ID");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 90, 30));

        txtfilm.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtfilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfilmActionPerformed(evt);
            }
        });
        jPanel3.add(txtfilm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 500, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Žanr");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 100, 30));

        txtzanr.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtzanr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtzanrActionPerformed(evt);
            }
        });
        jPanel3.add(txtzanr, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 500, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "FilmID", "Naziv", "Režiser", "Žanr", "Ocjena", "Godina"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 600, 220));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 710, 640));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnAdd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnAdd.setText("Add");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 190, 50));

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 190, 50));

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 190, 50));

        jbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 190, 50));

        jbtnedit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnedit.setText("Edit");
        jbtnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneditActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 190, 50));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 270, 640));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("FILMOVI");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 280, 60));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 960, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 1000, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtzanrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtzanrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtzanrActionPerformed

    private void txtocjenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtocjenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtocjenaActionPerformed

    private void txtgodinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgodinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgodinaActionPerformed
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Potvrdi svoj izlazak","Filmovi",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        
        
            String film= txtfilm.getText();
            String naziv= txtnaziv.getText();
            String reziser= txtreziser.getText();
            String zanr= txtzanr.getText();
            String ocjena= txtocjena.getText();
            String godina= txtgodina.getText();
        
         
            
            
            try{  
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/linda","root","");
            insert = con1.prepareStatement("insert into record(filmID,naziv,reziser,zanr,ocjena,godina)values(?,?,?,?,?,?)");
            
            insert.setString(1, film);
            insert.setString(2, naziv);
            insert.setString(3, reziser);
            insert.setString(4, zanr);
            insert.setString(5, ocjena);
            insert.setString(6, godina);
            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Film dodan");
            table_update();
            
            txtfilm.setText("");
            txtnaziv.setText("");
            txtreziser.setText("");
            txtzanr.setText("");
            txtocjena.setText("");
            txtgodina.setText("");
            txtfilm.requestFocus();
            
            
            
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Java_MysqlConn.class.getName()).log(Level.SEVERE, null, ex);
        }
         catch (SQLException ex) {
            Logger.getLogger(Java_MysqlConn.class.getName()).log(Level.SEVERE, null, ex);
        }   
      
        
    }//GEN-LAST:event_jbtnAddActionPerformed
 
    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        txtfilm.setText("");
        txtnaziv.setText("");
        txtreziser.setText("");
        txtzanr.setText("");
        txtocjena.setText("");
        txtgodina.setText("");
        txtfilm.requestFocus();
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
     
       DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
         int SelectedRows = jTable1.getSelectedRow();
         
         try{  
              int id = Integer.parseInt(df.getValueAt(SelectedRows, 0).toString());
              int dialogResult = JOptionPane.showConfirmDialog(null, "Želiš li izbrisati film?","Warning",JOptionPane.YES_NO_OPTION);
              
              if(dialogResult == JOptionPane.YES_OPTION)
              {
              
              Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/linda","root","");
            insert = con1.prepareStatement("delete from record where id =? ");
            
            
            insert.setInt(1, id);
              
              }
               
            insert.executeUpdate();
            
            
            JOptionPane.showMessageDialog(this, "Record Deleted");
            table_update();
            
            txtfilm.setText("");
            txtnaziv.setText("");
            txtreziser.setText("");
            txtzanr.setText("");
            txtocjena.setText("");
            txtgodina.setText("");
            txtfilm.requestFocus();
       
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Java_MysqlConn.class.getName()).log(Level.SEVERE, null, ex);
        }
         catch (SQLException ex) {
            Logger.getLogger(Java_MysqlConn.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
         int SelectedRows = jTable1.getSelectedRow();
         
         txtfilm.setText(df.getValueAt(SelectedRows, 1).toString());
         txtnaziv.setText(df.getValueAt(SelectedRows, 2).toString());
         txtreziser.setText(df.getValueAt(SelectedRows, 3).toString());
         txtzanr.setText(df.getValueAt(SelectedRows, 4).toString());
         txtocjena.setText(df.getValueAt(SelectedRows, 5).toString());
         txtgodina.setText(df.getValueAt(SelectedRows, 6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbtneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneditActionPerformed
        
         DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
         int SelectedRows = jTable1.getSelectedRow();
         
          try{  
              int id = Integer.parseInt(df.getValueAt(SelectedRows, 0).toString());
                 String film= txtfilm.getText();
                 String naziv= txtnaziv.getText();
                 String reziser= txtreziser.getText();
                 String zanr= txtzanr.getText();
                 String ocjena= txtocjena.getText();
                 String godina= txtgodina.getText();
              
              
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/linda","root","");
            insert = con1.prepareStatement("update record set filmID=?,naziv=?,reziser=?,zanr=?,ocjena=?,godina=? where id=? ");
            
            insert.setString(1, film);
            insert.setString(2, naziv);
            insert.setString(3, reziser);
            insert.setString(4, zanr);
            insert.setString(5, ocjena);
            insert.setString(6, godina);
            insert.setInt(7, id);
            
            
            insert.executeUpdate();
            
            
            JOptionPane.showMessageDialog(this, "Record updated");
            table_update();
            
            txtfilm.setText("");
            txtnaziv.setText("");
            txtreziser.setText("");
            txtzanr.setText("");
            txtocjena.setText("");
            txtgodina.setText("");
            txtfilm.requestFocus();
            
            
            
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Java_MysqlConn.class.getName()).log(Level.SEVERE, null, ex);
        }
         catch (SQLException ex) {
            Logger.getLogger(Java_MysqlConn.class.getName()).log(Level.SEVERE, null, ex);
        }   
         
         
         
         
    }//GEN-LAST:event_jbtneditActionPerformed

    private void txtfilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfilmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Java_MysqlConn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnedit;
    private javax.swing.JTextField txtfilm;
    private javax.swing.JTextField txtgodina;
    private javax.swing.JTextField txtnaziv;
    private javax.swing.JTextField txtocjena;
    private javax.swing.JTextField txtreziser;
    private javax.swing.JTextField txtzanr;
    // End of variables declaration//GEN-END:variables
}
